project:
  type: website

website:
  title: "quarto_test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: 'À propos'

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



